apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: shsp-falco-dd
  labels:
    falcoapp: falco-dd-celeryworker
  name: celeryworker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celeryworker
    spec:
      containers:
      - command:
        - /wait-for-it.sh
        - mysql:3306
        - -t
        - "30"
        - --
        - /entrypoint-celery-worker.sh
        env:
        - name: DD_CELERY_BROKER_PASSWORD
          value: guest
        - name: DD_CELERY_BROKER_USER
          value: guest
        - name: DD_DATABASE_URL
          value: mysql://defectdojo:defectdojo@mysql:3306/defectdojo
        image: defectdojo/defectdojo-django:latest
        name: celeryworker
        resources: {}
      restartPolicy: Always
status: {}
