apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: shsp-falco-dd
  labels:
    falcoapp: falco-dd-data
  name: defectdojo-data1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1024Mi
status: {}
