apiVersion: v1
kind: Service
metadata:
  namespace: shsp-falco-dd
  labels:
    falcoapp: falco-dd-nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 8080


  selector:
    falcoapp: falco-dd-nginx

  loadBalancerSourceRanges:
  - 35.188.192.110/32  # PrivateSharp All Repo Scanner
  - 35.208.194.182/32  #pritunl
  - 209.251.145.18/32  # sys
    #- 209.251.145.20/32  # dev - QA is on here atm

  type: LoadBalancer
