apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: shsp-falco-dd
  labels:
    falcoapp: falco-dd-rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.7
        name: rabbitmq
        resources: {}
      restartPolicy: Always
status: {}
